- name: Ansible win_command module example  
  hosts: win    
  tasks:
  - name: Create new Windows domain in a new forest with specific parameters
    ansible.windows.win_domain:
      create_dns_delegation: no
      database_path: C:\Windows\NTDS
      dns_domain_name: gptnvd.cloudnative.nvdlab.net
      domain_mode: Win2012R2
      domain_netbios_name: GPTNVD
      forest_mode: Win2012R2
      safe_mode_password: Nutanix.123
      sysvol_path: C:\Windows\SYSVOL
    register: domain_install
  - name: Reboot when domain feature requires it
    ansible.windows.win_reboot:
    when: domain_install.reboot_required
